# Generated by Django 4.1 on 2022-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topicos',
            new_name='Topico',
        ),
    ]
